// ─── Demo Fleet Data ───────────────────────────────────────────────────────
// Used as client-side fallback when the backend API returns an empty fleet.
// All slugs follow the route pattern:
//   /transport/[countrySlug]/[stateSlug]/transport-in-[citySlug]/[slug]

export interface DemoVehicle {
  id: number;
  name: string;
  slug: string;
  type: string;
  make: string;
  model: string;
  year: number;
  capacity: number; // seating
  luggageCapacity: number;
  transmission: "Manual" | "Automatic";
  fuelType: "Diesel" | "Petrol" | "CNG" | "Electric";
  isAc: boolean;
  pricePerKm: number;
  pricePerDay: number;
  images: string[];
  features: string[];
  highlights: string[];
  description: string;
  category: "economy" | "standard" | "premium" | "luxury";
  rating: number;
  reviewCount: number;
  ownerName: string;
  businessName: string;
  operatingSince: number;
  isVerified: boolean;
  badge?: string;
  // SEO route params
  countrySlug: string;
  stateSlug: string;
  destinationSlug: string; // used for citySlug in URL: transport-in-[destinationSlug]
  cityName: string;
}

export const DEMO_FLEET: DemoVehicle[] = [
  {
    id: 1,
    name: "Swift Dzire — Premium Cab",
    slug: "swift-dzire-premium-cab",
    type: "Cab",
    make: "Maruti Suzuki",
    model: "Swift Dzire ZXI+",
    year: 2023,
    capacity: 4,
    luggageCapacity: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    isAc: true,
    pricePerKm: 14,
    pricePerDay: 3200,
    images: [
      "https://images.unsplash.com/photo-1546614042-7df3c24c9e5d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["Full AC", "GPS Tracking", "Music System", "USB Charging", "First Aid Kit", "Fire Extinguisher"],
    highlights: ["Best Economy Choice", "City & Outstation", "24/7 Available"],
    description: "Our premium Swift Dzire fleet is perfect for couples and small families. Fuel-efficient, comfortable, and maintained to the highest standards. Ideal for city transfers, airport pickups, and short outstation trips.",
    category: "economy",
    rating: 4.7,
    reviewCount: 124,
    ownerName: "Rajesh Kumar",
    businessName: "Himalayan Cab Services",
    operatingSince: 2018,
    isVerified: true,
    badge: "Most Booked",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "manali",
    cityName: "Manali",
  },
  {
    id: 2,
    name: "Toyota Innova Crysta — 7 Seater",
    slug: "toyota-innova-crysta-7-seater",
    type: "Cab",
    make: "Toyota",
    model: "Innova Crysta GX",
    year: 2022,
    capacity: 7,
    luggageCapacity: 4,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 18,
    pricePerDay: 5500,
    images: [
      "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600705722908-babe3e3c89a2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1490902931801-d6f80ca94fe4?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["Dual AC", "GPS Tracking", "Reclining Seats", "USB Charging", "Large Boot", "Child Seat Option"],
    highlights: ["Family Favourite", "Mountain Ready", "Hill Station Expert"],
    description: "The Toyota Innova Crysta is the most trusted SUV for Himalayan travel. Powerful diesel engine handles mountain terrains with ease. Spacious enough for a family of 7 with full luggage. Our Crystas are diesel-powered, ensuring best performance at high altitudes.",
    category: "standard",
    rating: 4.9,
    reviewCount: 287,
    ownerName: "Suresh Thakur",
    businessName: "Mountain Drive Pvt. Ltd.",
    operatingSince: 2015,
    isVerified: true,
    badge: "Top Rated",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "manali",
    cityName: "Manali",
  },
  {
    id: 3,
    name: "Mahindra Scorpio — 9 Seater",
    slug: "mahindra-scorpio-9-seater",
    type: "Cab",
    make: "Mahindra",
    model: "Scorpio S11 4WD",
    year: 2023,
    capacity: 9,
    luggageCapacity: 3,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 16,
    pricePerDay: 5000,
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["4WD", "Hill Assist", "GPS Tracking", "AC", "Roof Carrier", "Recovery Gear"],
    highlights: ["Off-Road Capable", "Snow Ready", "Adventure Grade"],
    description: "The Mahindra Scorpio 4WD is the ultimate adventure vehicle for Spiti Valley, Rohtang Pass, and high-altitude Himalayan routes. 4-wheel drive ensures safety on snow and gravel. Preferred by trekking groups and adventure enthusiasts.",
    category: "standard",
    rating: 4.8,
    reviewCount: 156,
    ownerName: "Vikas Negi",
    businessName: "Spiti Adventure Tours",
    operatingSince: 2017,
    isVerified: true,
    badge: "Adventure Pick",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "manali",
    cityName: "Manali",
  },
  {
    id: 4,
    name: "Force Tempo Traveller — 12 Seater",
    slug: "force-tempo-traveller-12-seater",
    type: "Tempo",
    make: "Force Motors",
    model: "Traveller 12+1 Deluxe",
    year: 2022,
    capacity: 12,
    luggageCapacity: 8,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 24,
    pricePerDay: 9000,
    images: [
      "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598953431148-1929f75cc72d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564182842519-8a3b2af3e228?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["Push-Back Seats", "Dual AC", "Reading Lights", "Curtains", "Music System", "Water Bottle Holders"],
    highlights: ["Group Specialist", "Push-Back Seats", "Double Blower AC"],
    description: "Our 12-seater Tempo Traveller fleet is the top choice for group pilgrimages, corporate outings, and family trips. Equipped with push-back aircraft-style seats, dual AC blowers, and curtained windows for complete privacy. Perfect for routes like Chandigarh-Manali and Delhi-Shimla.",
    category: "premium",
    rating: 4.7,
    reviewCount: 198,
    ownerName: "Anil Sharma",
    businessName: "Group Tours Himachal",
    operatingSince: 2016,
    isVerified: true,
    badge: "Group Favourite",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "manali",
    cityName: "Manali",
  },
  {
    id: 5,
    name: "Force Tempo Traveller — 17 Seater",
    slug: "force-tempo-traveller-17-seater",
    type: "Tempo",
    make: "Force Motors",
    model: "Traveller 17+1 AC",
    year: 2023,
    capacity: 17,
    luggageCapacity: 12,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 28,
    pricePerDay: 12000,
    images: [
      "https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1546614042-7df3c24c9e5d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["17 Push-Back Seats", "Triple AC", "Overhead Storage", "Charging Ports", "LED Lights", "Emergency Kit"],
    highlights: ["Large Group", "Corporate Trips", "Pilgrimage Ready"],
    description: "The 17-seater Tempo Traveller handles large group travel like a pro. Triple AC zones keep every passenger cool. Overhead storage bins for hand luggage. Regularly serviced with strict safety inspection. Ideal for corporate groups, wedding guests, and religious tours to Vaishno Devi or Char Dham.",
    category: "premium",
    rating: 4.6,
    reviewCount: 143,
    ownerName: "Deepak Rawat",
    businessName: "Himalayan Group Movers",
    operatingSince: 2019,
    isVerified: true,
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "shimla",
    cityName: "Shimla",
  },
  {
    id: 6,
    name: "Force Tempo Traveller — 26 Seater",
    slug: "force-tempo-traveller-26-seater",
    type: "Tempo",
    make: "Force Motors",
    model: "Traveller 26+1 AC Deluxe",
    year: 2022,
    capacity: 26,
    luggageCapacity: 20,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 35,
    pricePerDay: 18000,
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540638349517-3abd5afc5847?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1594818898109-44704d4bdf6a?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["26 Reclining Seats", "Quad AC", "Digital Music", "Window Curtains", "Luggage Rack", "Fire Safety"],
    highlights: ["XL Group", "School Trips", "Conference Transport"],
    description: "Our flagship 26-seater serves large group travel requirements. Equipped with four-zone AC, individual reclining seats, and extra luggage compartment. Preferred for school excursions, college trips, and large corporate delegations.",
    category: "premium",
    rating: 4.5,
    reviewCount: 89,
    ownerName: "Mohit Thakur",
    businessName: "Large Group Travels",
    operatingSince: 2014,
    isVerified: true,
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "shimla",
    cityName: "Shimla",
  },
  {
    id: 7,
    name: "Volvo 9600 Multi-Axle Coach",
    slug: "volvo-9600-coach",
    type: "Coach",
    make: "Volvo",
    model: "9600 B11R Semi-Sleeper",
    year: 2023,
    capacity: 40,
    luggageCapacity: 30,
    transmission: "Automatic",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 55,
    pricePerDay: 35000,
    images: [
      "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1526667171755-9c3f1c900e01?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550659408-2fc9c3b84d31?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559076294-ad5d6addc5b4?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["40 Push-Back Seats", "6-Zone AC", "Onboard Entertainment", "WiFi", "Reading Lights", "3-Point Seatbelts"],
    highlights: ["Luxury Coach", "WiFi Onboard", "Overnight Journeys"],
    description: "Experience the pinnacle of group travel with our Volvo 9600 coach. Features 40 semi-sleeper reclining seats, multi-zone AC, onboard WiFi, and individual entertainment screens. The automated gearbox ensures smooth and safe operation on mountain highways. Used for premium tour packages and conference logistics.",
    category: "luxury",
    rating: 4.9,
    reviewCount: 76,
    ownerName: "Amarjeet Singh",
    businessName: "Volvo Travel Pvt. Ltd.",
    operatingSince: 2012,
    isVerified: true,
    badge: "Luxury",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "chandigarh",
    cityName: "Chandigarh",
  },
  {
    id: 8,
    name: "Tata Winger — 9 Seater Minivan",
    slug: "tata-winger-9-seater-minivan",
    type: "Tempo",
    make: "Tata",
    model: "Winger Platinum DX",
    year: 2022,
    capacity: 9,
    luggageCapacity: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 20,
    pricePerDay: 7500,
    images: [
      "https://images.unsplash.com/photo-1598953431148-1929f75cc72d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1546614042-7df3c24c9e5d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["9 Captain Seats", "Dual AC", "Bluetooth Music", "Power Windows", "Reverse Camera", "USB Charging"],
    highlights: ["Small Group", "Weekend Trips", "Airport Shuttle"],
    description: "The Tata Winger is a premium compact minivan ideal for small groups of 7–9 passengers. Individual captain seats, dual AC, and Bluetooth connectivity ensure a first-class experience. Popular for airport transfers and weekend Himalayan escapes.",
    category: "standard",
    rating: 4.6,
    reviewCount: 112,
    ownerName: "Pankaj Rana",
    businessName: "Winger Travels Manali",
    operatingSince: 2020,
    isVerified: true,
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "manali",
    cityName: "Manali",
  },
  {
    id: 9,
    name: "Mercedes Sprinter — Luxury Van",
    slug: "mercedes-sprinter-luxury-van",
    type: "Tempo",
    make: "Mercedes-Benz",
    model: "Sprinter 313 CDI",
    year: 2023,
    capacity: 14,
    luggageCapacity: 10,
    transmission: "Automatic",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 45,
    pricePerDay: 22000,
    images: [
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["14 Luxury Seats", "Climate Control", "LED Ambient Lighting", "Mini Fridge", "WiFi", "Individual Screens"],
    highlights: ["Ultra Luxury", "Corporate Premium", "Wedding Transport"],
    description: "The Mercedes Sprinter represents the pinnacle of van luxury in our fleet. Bespoke leather captain chairs, ambient LED lighting, individual 10-inch screens, and a stocked mini fridge. Perfect for VIP transfers, wedding transport, and premium corporate events. The automatic transmission ensures a silky-smooth drive on mountain roads.",
    category: "luxury",
    rating: 5.0,
    reviewCount: 42,
    ownerName: "Rohan Mehta",
    businessName: "Elite Mobility Solutions",
    operatingSince: 2021,
    isVerified: true,
    badge: "VIP",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "chandigarh",
    cityName: "Chandigarh",
  },
  {
    id: 10,
    name: "Ashok Leyland Coach — 35 Seater",
    slug: "ashok-leyland-coach-35-seater",
    type: "Coach",
    make: "Ashok Leyland",
    model: "Viking R Coach AC",
    year: 2022,
    capacity: 35,
    luggageCapacity: 25,
    transmission: "Manual",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 45,
    pricePerDay: 28000,
    images: [
      "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1550659408-2fc9c3b84d31?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1526667171755-9c3f1c900e01?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["35 Reclining Seats", "5-Zone AC", "PA System", "2x2 Seating", "Luggage Belly", "First Aid"],
    highlights: ["Mid-Size Coach", "Tour Groups", "Value Coach"],
    description: "The Ashok Leyland 35-seater coach is a mainstay for mid-size tour groups. Full AC with 5 zones, 2×2 seating configuration, public address system, and belly cargo compartment. Excellent value for money for religious tours, school trips, and cultural programs.",
    category: "premium",
    rating: 4.4,
    reviewCount: 93,
    ownerName: "Gurpreet Singh",
    businessName: "Punjab Tours & Travels",
    operatingSince: 2013,
    isVerified: true,
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "chandigarh",
    cityName: "Chandigarh",
  },
  {
    id: 11,
    name: "Hyundai Creta — Premium SUV",
    slug: "hyundai-creta-premium-suv",
    type: "Cab",
    make: "Hyundai",
    model: "Creta SX(O) Turbo DCT",
    year: 2024,
    capacity: 5,
    luggageCapacity: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    isAc: true,
    pricePerKm: 17,
    pricePerDay: 4500,
    images: [
      "https://images.unsplash.com/photo-1605559424843-9073c6e43691?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1548731111-cbaf45a32c1f?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["Panoramic Sunroof", "Connected Car Tech", "ADAS Safety Suite", "Wireless Charging", "360-Camera", "Ventilated Seats"],
    highlights: ["Brand New 2024", "Sunroof", "ADAS Safety"],
    description: "Our brand new 2024 Hyundai Creta SX(O) Turbo is the most feature-loaded compact SUV in the fleet. Panoramic sunroof, ADAS safety suite, wireless charging, 360-degree camera, and ventilated seats make it a premium experience. Perfect for couples and families seeking comfort with a touch of adventure.",
    category: "premium",
    rating: 4.8,
    reviewCount: 67,
    ownerName: "Priya Kapoor",
    businessName: "Premium Drive Solutions",
    operatingSince: 2022,
    isVerified: true,
    badge: "New 2024",
    countrySlug: "india",
    stateSlug: "himachal-pradesh",
    destinationSlug: "shimla",
    cityName: "Shimla",
  },
  {
    id: 12,
    name: "Land Cruiser Prado — VIP SUV",
    slug: "land-cruiser-prado-vip-suv",
    type: "Cab",
    make: "Toyota",
    model: "Land Cruiser Prado TXL",
    year: 2023,
    capacity: 7,
    luggageCapacity: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    isAc: true,
    pricePerKm: 60,
    pricePerDay: 18000,
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1609752679570-2e1022aaa1f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1563720360172-67b8f3dce741?auto=format&fit=crop&w=800&q=80",
    ],
    features: ["AWD with Crawl Control", "Kinetic Dynamic Suspension", "Multi-Terrain Select", "JBL Surround Sound", "Heated Leather Seats", "Night Vision Assist"],
    highlights: ["Extreme Terrain", "High Altitude", "Leh-Ladakh Specialist"],
    description: "The Toyota Land Cruiser Prado is the undisputed king of Himalayan travel. Built for extreme terrain with Crawl Control, Multi-Terrain Select, and Kinetic Dynamic Suspension. Has proven itself on the Manali-Leh highway, Spiti Valley, and Rohtang Pass countless times. Ultimate VIP comfort meets unmatched capability.",
    category: "luxury",
    rating: 5.0,
    reviewCount: 38,
    ownerName: "Chetan Singh Negi",
    businessName: "Himalayan Legends Transport",
    operatingSince: 2010,
    isVerified: true,
    badge: "Flagship",
    countrySlug: "india",
    stateSlug: "jammu-kashmir",
    destinationSlug: "leh",
    cityName: "Leh",
  },
];

export const DEMO_ROUTES = [
  { id: 1, from: "Chandigarh", to: "Manali", distance: 310, estimatedTime: "8–9 hrs", startingPrice: 8000, isPopular: true },
  { id: 2, from: "Delhi", to: "Manali", distance: 540, estimatedTime: "14–15 hrs", startingPrice: 14000, isPopular: true },
  { id: 3, from: "Chandigarh", to: "Shimla", distance: 118, estimatedTime: "3–4 hrs", startingPrice: 3500, isPopular: true },
  { id: 4, from: "Manali", to: "Leh", distance: 480, estimatedTime: "14–16 hrs", startingPrice: 16000, isPopular: true },
  { id: 5, from: "Delhi", to: "Leh", distance: 1020, estimatedTime: "2 Days", startingPrice: 28000, isPopular: false },
  { id: 6, from: "Chandigarh", to: "Dharamshala", distance: 248, estimatedTime: "5–6 hrs", startingPrice: 6000, isPopular: true },
];
